### ISSUE TITLE
[Query] Minimum Requirements to visualise the learnt model

### ISSUE THREAD

**Issue by Acejoy** [OSU-NLP-Group/LLM-Planner#11]
Hello all,
I am interested in this project and want to run it on my local machine. I wanted to know what was the minimum hardware requirements for running this code?
I have 16GB RAM, 4GB Nvidia Geforce 1650Ti and running on Ubuntu 22.04 LTS.

thanks

**Comment by chanhee-luke** [comment]
This doesn’t need GPU to run. I’ve only tested on MacOS and Ubuntu 20.04 but should work on 22.04.

**Comment by Acejoy** [comment]
Sorry, If I understand correctly: We use semantic segmentation for visual understanding and LLM as an action planner, so the leanrt models do not require GPU? Please correct me if I am wrong.

Sorry, if my questions are too trivial, I am still learning.

**Comment by chanhee-luke** [comment]
The model can be run on CPU. GPU makes the inference faster but it is not required.

**Comment by Acejoy** [comment]
> The model can be run on CPU. GPU makes the inference faster but it is not required.

Thanks again for the reply.
