### ISSUE TITLE
A contradiction: the unity interface does not exit and there is no OpenAI module. Is this an issue with the Python version

### ISSUE THREAD

**Issue by sunpengfei001** [OSU-NLP-Group/LLM-Planner#12]
Hi there,
I built the environment for LLM Planner on a virtual machine on Ubuntu 18.04, and created two virtual environments using Anaconda: the first virtual environment, robo, uses version 3.6 of Python; The second virtual environment, alftest, uses version 3.9 of Python.
When I executed the [Python scripts/check_thor. py] command in the robo environment, It downloaded "thor-201909061227" and a Unity interface popped up, similar to the [MoveAhead] command in the “check_thor. Py” script, the interface quickly moved forward, then the Unity interface quickly exited, and the shape of the event and "Everything works!!!" were outputted (I attached a picture at the end). I think this is the correct operating state.
But when I ran the script using the Python 3.9 environment alftest, the Unity interface appeared and quickly moved forward. After that, the interface never exited and got stuck here. I even waited for a few hours, but the Unity interface still stopped here (I also attached a picture at the end), I don't know what's going on? I have conducted several tests on this virtual machine and found that this issue occurs in both Python 3.7 and Python 3.8 virtual environments, but Python 3.6 virtual environments can execute normally.
If I use the virtual environment of Python 3.6 to perform subsequent operations, such as running the [python run_eval. py -- config gpt4_base_config. yaml] command, it will also prompt that there is no OpenAI module in OpenAI. This is an issue with the OpenAI version. In the virtual environment of Python 3.6, the highest version of OpenAI can only reach 0.8.0, and this version does not have an OpenAI module, so it cannot run "run_eval. py".
If using a virtual environment higher than Python 3.6 to execute the "run_eval. py" script, the same issue will occur as before, that is, the Unity interface will not exit (I have also attached a picture later).
Therefore, there is a contradiction here. When using a virtual environment higher than Python 3.6 (such as Python 3.9),  there will be a problem of the Unity interface not exiting when running "run_eval. py"; However, using a virtual environment with Python 3.6, due to the lack of OpenAI modules, it is even impossible to run the "run_eval. py" script, resulting in direct errors.
How can I solve this problem? What environment are the people you successfully run in?
Looking forward to your reply!

![pic1](https://github.com/OSU-NLP-Group/LLM-Planner/assets/85286643/0633d84e-b999-4cbe-a82c-88b18e16b63c)
![pic2](https://github.com/OSU-NLP-Group/LLM-Planner/assets/85286643/2f13e4e4-0a7f-4a4b-b66c-d1fa0a72f3de)
![pic3](https://github.com/OSU-NLP-Group/LLM-Planner/assets/85286643/7eb91755-781d-4db7-bf64-65cc029f4106)

**Comment by chanhee-luke** [comment]
Hi I believe this is an issue related to #9, we are working on refactoring the code to support variety of open-source and closed-source models so please check back soon!

**Comment by yun-hu** [comment]
Hi I have the same problem. Have you solved it?

**Comment by chuangwaipiaoluohuaxiang** [comment]
I have the same problem. Have you solved the problem yet?
Thank you for your reply.

**Comment by sunpengfei001** [comment]
Sorry, it hasn't been resolved yet. I'm waiting for the author to refactor the code

**Comment by LightCheat** [comment]
你好，我遇到了相同的问题，我在debug的时候发现好像由于是gym包太新导致的这里会卡住，可以尝试降级gym包

**Comment by sunpengfei001** [comment]
> 你好，我遇到了相同的问题，我在debug的时候发现好像由于是gym包太新导致的这里会卡住，可以尝试降级gym包

感谢你的提示，我之后去尝试一下。

**Comment by chuangwaipiaoluohuaxiang** [comment]
> 你好，我遇到了相同的问题，我在debug的时候发现好像由于是gym包太新导致的这里会卡住，可以尝试降级gym包

你好，我在重新安装gym时，出现alfworld 0.2.2需要gym==0.15.4，但你有不兼容的gym 0.10.0。请问你如何解决了这个问题呢？

**Comment by LightCheat** [comment]
> > 你好，我遇到了相同的问题，我在debug的时候发现好像由于是gym包太新导致的这里会卡住，可以尝试降级gym包
> 
> 你好，我在重新安装gym时，出现alfworld 0.2.2需要gym==0.15.4，但你有不兼容的gym 0.10.0。请问你如何解决了这个问题呢？

我忘记了当时具体怎么做的，我重新新建了好几次环境。不断的更改可能造成问题的包的版本，最后就莫名其妙的好用了。我使用的python版本是3.9，你可以尝试使用3.9建立一个环境重新安装依赖试试

**Comment by LightCheat** [comment]
> > 你好，我遇到了相同的问题，我在debug的时候发现好像由于是gym包太新导致的这里会卡住，可以尝试降级gym包
> 
> 感谢你的提示，我之后去尝试一下。

抱歉，我可能记错了。我当时尝试配置的时候遇到了很多问题。你可以试试重新配置一个环境，然后aflworld安装最新的版本0.3.3

**Comment by BatmanofZuhandArrgh** [comment]
FYI I think we got the same error, and i found the solution https://github.com/OSU-NLP-Group/LLM-Planner/issues/15. I ended up just installing the latest alfworld from source

**Comment by chanhee-luke** [comment]
We are currently working on replacing the ALFWorld backbone since it's not easily compatible with other datasets/simulators and MLLMs so in the meantime I recommend using this codebase (https://github.com/lbaa2022/LLMTaskPlanning). Please look out for the revamped codebase soon.

**Comment by WZX0Swarm0Robotics** [comment]
> > 你好，我遇到了相同的问题，我在debug的时候发现好像由于是gym包太新导致的这里会卡住，可以尝试降级gym包
> 
> 你好，我在重新安装gym时，出现alfworld 0.2.2需要gym==0.15.4，但你有不兼容的gym 0.10.0。请问你如何解决了这个问题呢？



> > > 你好，我遇到了相同的问题，我在debug的时候发现好像由于是gym包太新导致的这里会卡住，可以尝试降级gym包
> > 
> > 
> > 你好，我在重新安装gym时，出现alfworld 0.2.2需要gym==0.15.4，但你有不兼容的gym 0.10.0。请问你如何解决了这个问题呢？
> 
> 我忘记了当时具体怎么做的，我重新新建了好几次环境。不断的更改可能造成问题的包的版本，最后就莫名其妙的好用了。我使用的python版本是3.9，你可以尝试使用3.9建立一个环境重新安装依赖试试

我也遇到同样的问题了，我重新指定python=3.9，创建虚拟环境后，按照步骤再次配置环境，就解决了，希望这能对你有帮助
