### ISSUE TITLE
The pre-defined actions don't not work

### ISSUE THREAD

**Issue by qijinshe** [OSU-NLP-Group/LLM-Planner#9]
Hi there,

Thanks for your release of the excellent work!

I have successfully run your code, but I found that the pre-defined actions like "Navigation [Object]" cannot be executed successfully when sent to the modified simulated environment. The environment state doesn't change and the simulator outputs "Nothing happens".  I referred to the original simulator (alfworld) and found that their pre-defined actions are not the same as yours. I would like to know whether you have modified the pre-defined actions and how can I make the right action commands run in your environment.

In addition, I found that the alfworld environment you modified does not have the “env” module. I found the corresponding code in the original repository and placed it in the corresponding directory. Could this be the reason why the environment cannot run action commands correctly?

Look forward to your reply!

**Comment by chanhee-luke** [comment]
Hi, we did change the action definition. Check the parse_command method at https://github.com/OSU-NLP-Group/LLM-Planner/blob/main/alfworld/alfworld/agents/controller/base.py. This transforms the LLM generated high-level plan to ALFWORLD compatible actions.

I’ll take a look and get back to you. Can you tell me your computing setup and environment information? Thanks and happy new year!

**Comment by qijinshe** [comment]
Here is my basic environment and computing information: python=3.9,  ai2thor=2,1,  torch=1.12.1+cu113,  cpu=RTX3090.

I checked the code based on your suggestion and found that the program casts an error in the "step" function in  https://github.com/OSU-NLP-Group/LLM-Planner/blob/main/alfworld/alfworld/agents/controller/Oracle.py. 

I am trying to figure out what causes the error. Following is the TraceBack: 
'''
Traceback (most recent call last):
    File "/home/qijin/anaconda3/envs/LLM_Planner2/lib/python3.9/site-packages/alfworld/agents/controller/oracle.py", line 175, in step
      self.curr_loc = recep['locs']
  TypeError: 'NoneType' object is not subscriptable
'''
 I will update the information.

Thanks for your quick reply and wish you a happy new year!

**Comment by siifish** [comment]
I've also encountered the same problem, which is that the environment fails to successfully run 'act', and it keeps returning 'nothing happens'. I look forward to your reply as I am also searching for a solution. And Happy New Year! @chanhee-luke @qijinshe

**Comment by chanhee-luke** [comment]
Hi @siifish could you also tell me your computing environment? 

@qijinshe Were you able to solve it? I couldn’t replicate on my end. I’m currently re-applying my changes to a fresh ALFWORLD clone to find out the root cause. What’s your OS version?

**Comment by qijinshe** [comment]
@chanhee-luke Not yet. I think there may be some problems with "get_object" function in the base.py? I have run the original alfworld program and the instructions can be executed correctly. The function in the original file is slightly different from your version.

**Comment by siifish** [comment]
@chanhee-luke Thanks for your quick reply! 
Here is my basic environment and computing information: python=3.8, ai2thor=2.1.0, alfworld=0.2.2, textworld=1.5.4, torch=1.13.1+cu116, gpu=TITAN XP, and system ubuntu18.04.

**Comment by siifish** [comment]
@qijinshe May I ask how you successfully run the code?
I have downloaded the code from the ALFWorld official website and replaced the original ALFWorlf folder, but it still keeps outputting 'nothing happens'.
Which version of ALFWorld did you are you using?

**Comment by siifish** [comment]
@chanhee-luke Could you tell me the versions of the `textworld` and `alfworld` packages in your environment? I suspect that the versions of the `textworld` and `alfworld` packages in my environment might be mismatched.

**Comment by Acejoy** [comment]
Hello @siifish , were you able to run the code? If yes, may I know your system details. I myself want to try out the code and was enquiring about the system requirements.Thanks

**Comment by chanhee-luke** [comment]
Hi everyone. We are currently refactoring code to support open source models and different datasets/simulators. I hope that will fix this issue too. Please be patient. Thank you!
